构建的镜像可以在创建的docker中运行systemctl

dockerfile内容

FROM centos:7
MAINTAINER “yang” yang@email.here
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); rm -f /lib/systemd/system/multi-user.target.wants/;rm -f /etc/systemd/system/.wants/;rm -f /lib/systemd/system/local-fs.target.wants/;rm -f /lib/systemd/system/sockets.target.wants/udev;rm -f /lib/systemd/system/sockets.target.wants/initctl;rm -f /lib/systemd/system/basic.target.wants/;rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ “/sys/fs/cgroup” ]
CMD ["/usr/sbin/init"]


命令
docker build --rm -t docker-images .

构建的镜像可以在创建的docker中运行systemctl

启动docker命令 
docker run -itd --privileged --name=dockername docker-images-name



参考链接：https://www.cnblogs.com/ding2016/p/6756941.html
