FROM centos:6.9
RUN yum install -y epel-release wget && \
    mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
    wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo && \
    yum makecache && yum install -y gcc vim git rsyslog lsof && mkdir -p /home/work && \
    mkdir /root/.ssh/
ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN rpm -i https://centos6.iuscommunity.org/ius-release.rpm && \
    yum --enablerepo=ius-archive install -y python27 python27-pip python27-libs python27-devel python27-setuptools && \
    ssh-keyscan 12.1.1 >> /root/.ssh/known_hosts && \
    git clone git@1.2.2.6:test/apm.git /home/work/apm
ADD NSUPDATE.py /home/work/apm/lib/apm/constants/
ADD NODE.py /home/work/apm/lib/apm/constants/
RUN cd /home/work/apm/env/ && sh install_env.sh && \
    cd /home/work/apm/scripts/ && sh change_config.sh test && \
    mkdir /home/work/apm/redis-2.6.13/log && mkdir /home/work/apm/redis-2.6.13/dump && \
    echo '/home/work/apm/redis-2.6.13/bin/redis-server /home/work/apm/redis-2.6.13/conf/redis.master.conf' >> /home/work/apm/prepare.sh && \
    echo '/home/work/apm/redis-2.6.13/bin/redis-server /home/work/apm/redis-2.6.13/conf/sentinel.conf --sentinel' >> /home/work/apm/prepare.sh && \
    echo 'service rsyslog restart' >> /home/work/apm/prepare.sh && \
    echo 'echo "1.2.1.1  dev-boss-api.baidu.com" >> /etc/hosts' >> /home/work/apm/prepare.sh
